package:
  name: freeimage
  version: "3.17.0"

source:
  fn: FreeImage3170.zip
  url: https://downloads.sourceforge.net/project/freeimage/Source%20Distribution/3.17.0/FreeImage3170.zip
  sha256: fbfc65e39b3d4e2cb108c4ffa8c41fd02c07d4d436c594fff8dab1a6d5297f89

  patches:
    - osx_makefile.patch [osx]

about:
  home: https://sourceforge.net/projects/freeimage
  license: GPLv2, GPLv3, FIPL
